Downgrade mocha
Tests run in local environment, but in Github actions they can't handle the syntax:
```
> nightscout-fhir-connect@1.4.20 test /home/runner/work/nightscout-fi/nightscout-fi
79
> env-cmd ./test.env react-scripts test --env=jsdom && env-cmd ./test.env mocha --exit --timeout 8000 --require esm tests/*.test.js
80

81
PASS src/Routes/Routes.test.js
82
  ✓ renders without crashing (66 ms)
83

84
Test Suites: 1 passed, 1 total
85
Tests:       1 passed, 1 total
86
Snapshots:   0 total
87
Time:        3.176 s
88
Ran all test suites.
89

90
/home/runner/work/nightscout-fi/nightscout-fi/tests/fhirclient.test.js:1
91
(function (exports, require, module, __filename, __dirname) { import { v4 as uuidv4 } from 'uuid';
92
                                                              ^^^^^^
93

94
SyntaxError: Cannot use import statement outside a module
95
    at new Script (vm.js:102:7)
96
    at createScript (vm.js:262:10)
97
    at Object.runInThisContext (vm.js:310:10)
98
    at wrapSafe (internal/modules/cjs/loader.js:989:15)
99
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
100
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
101
    at Module.load (internal/modules/cjs/loader.js:950:32)
102
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
103
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
104
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
105
    at async Loader.import (internal/modules/esm/loader.js:178:24)
106
    at async formattedImport (/home/runner/work/nightscout-fi/nightscout-fi/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
107
    at async Object.exports.requireOrImport (/home/runner/work/nightscout-fi/nightscout-fi/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
108
    at async Object.exports.loadFilesAsync (/home/runner/work/nightscout-fi/nightscout-fi/node_modules/mocha/lib/nodejs/esm-utils.js:88:20)
109
    at async singleRun (/home/runner/work/nightscout-fi/nightscout-fi/node_modules/mocha/lib/cli/run-helpers.js:125:3)
110
    at async Object.exports.handler (/home/runner/work/nightscout-fi/nightscout-fi/node_modules/mocha/lib/cli/run.js:374:5)
111
npm ERR! Test failed.  See above for more details.
112
Error: Process completed with exit code 1.
```